---
title: "Measuring Student Success in MA050 & Beyond"
authors: Shannon Coyle & Rachel Kempter
output: html_notebook
---

```{r}
library(mosaic)
library(dplyr)
library(reshape2) # dcast
library(data.table) # rowid
```

```{r}
# Initializing the dataset to a variable - dataset is updated but has spring/22 in it
# math.students = MathData2Cleaner3
# math.students <- as.data.frame(math.students)
```

```{r}
# Initializing dataset to a variable - has all data from 99
math.students <- Finalized_Coyle_Data
math.students <- as.data.frame(math.students)
```


```{r}
# Manipulating the names of the columns so they are easier to call in the future
math.students = math.students %>% 
  rename(
    id = 'Student ID', 
    term = 'Term',
    active.major = 'ACT MAJ',
    active.programs = 'Active Programs',
    course.name = 'Course Name',
    section.name = 'Section Name',
    current.status = 'Current Status',
    midterm.grade = 'MIDTERM GRADE',
    verif.grade = 'Verif Grade',
    final.grade = 'Final Grade',
    completed.credits = 'Cmpl Cred',
    faculty.last = 'Faculty Last Name', 
    math.placement.score = 'M89 Stu Recent Math Placement',
    ug.completed.credits = 'CMPL CREDS UG',
    degree = 'Degree',
    degree.description = 'Degree Desc',
    majors = 'Majors',
    major.description = 'Major', 
    date = 'Date**'
    
  )
```

```{r}
# Removing all empty IDs
math.students <- subset(math.students, !(is.na(math.students$id)))
```

## Splitting the data based on column names to see frequency of each
```{r}
# Creating a split list of math students based on their ids and grouping them together
split.by.id <- split(math.students, f = math.students$id)
```

```{r}
# Creating a split list of courses
split.by.ma050 <- split(math.students, f = math.students$course.name)
```

```{r}
# Creating a split list based on term taken
split.by.term <- split(math.students, f = math.students$term)
```

```{r}
# Creating a split list based on student current status
split.by.current.status <- split(math.students, f = math.students$current.status)
```

```{r}
# Creating a split list based on grade received in course
split.by.verif.grade <- split(math.students, f = math.students$verif.grade)
```

## Further condensing each of the dataframes
```{r}
# Omitting the Spring 22 students
terms <- c()

for(i in 1:length(split.by.term)) {
  if(split.by.term[[i]]$term != "22/SP" && split.by.term != "") {
    terms <- c(terms, split.by.term[i])
  }
}
```

```{r}
# Initializing a dataframe to be populated with ids that occur twice or more
more.than.two.grades <- c()

for(i in 1:length(split.by.id)) {
  if(nrow(split.by.id[[i]]) >= 2) {
    more.than.two.grades <- c(more.than.two.grades, split.by.id[i])
  }
}
```

```{r}
# Initializing a dataframe to be populated with ids that occur only twice
only.two.grades <- c()

for(i in 1:length(split.by.id)) {
  if(nrow(split.by.id[[i]]) == 2) {
   only.two.grades <- c(only.two.grades, split.by.id[i])
  }
}
```

```{r}
# Adding COVID semesters into its own dataframe to see if there is a difference in grades
covid.terms <- c()

for(i in 1:length(split.by.term)) {
  if(split.by.term[[i]]$term == "20/SP" || split.by.term[[i]]$term == "20/SA" || split.by.term[[i]]$term == "20/SB" ||  split.by.term[[i]]$term == "20/SC" || split.by.term[[i]]$term == "20/SD" || split.by.term[[i]]$term == "20/SE" || split.by.term[[i]]$term == "20/FA" || split.by.term[[i]]$term == "21/SP" || split.by.term[[i]]$term == "21/SA" || split.by.term[[i]]$term == "21/SB" ||  split.by.term[[i]]$term == "21/SC" || split.by.term[[i]]$term == "21/SD" || split.by.term[[i]]$term == "21/SE") {
    covid.terms <- c(covid.terms, split.by.term[i])
  }
}
```

## Building a data frame with all data from the dataset
```{r}
# data frame with grades
df = reshape2::dcast(math.students, id + active.major + active.programs ~ rowid(id), value.var = "final.grade")
colnames(df) = c("ID", "ACT_MAJ", "Active_Programs", "Grade1", "Grade2", "Grade3", "Grade4", "Grade5", "Grade6")

# data frame with terms
term = reshape2::dcast(math.students, id ~ rowid(id), value.var = "term")
term = subset(term, select = -c(id))
colnames(term) = c("Term1", "Term2", "Term3", "Term4", "Term5", "Term6")

# data frame with course codes
name = reshape2::dcast(math.students, id ~ rowid(id), value.var = "course.name")
name = subset(name, select = -c(id))
colnames(name) = c("Course1", "Course2", "Course3", "Course4", "Course5", "Course6")

# data frame with profs
prof = reshape2::dcast(math.students, id ~ rowid(id), value.var = "faculty.last")
prof = subset(prof, select = -c(id))
colnames(prof) = c("Prof1", "Prof2", "Prof3", "Prof4", "Prof5", "Prof6")

# merge all data frames above to one data frame
all.data.frames = cbind(df, term, name, prof)

# reorder the columns in the merged data frame
ordered.data.frame <- subset(all.data.frames, select = c("ID", "ACT_MAJ", "Active_Programs", "Prof1", "Term1", "Course1", "Grade1", "Prof2", "Term2", "Course2", "Grade2", "Prof3", "Term3", "Course3", "Grade3", "Prof4", "Term4", "Course4", "Grade4", "Prof5", "Term5", "Course5", "Grade5", "Prof6", "Term6", "Course6", "Grade6"))

```

```{r}
# Removing anyone who has 050 as a second course since that means they failed the first time they took it
ordered.data.frame <- subset(ordered.data.frame, ordered.data.frame$Course2 != "MA-050")

# Removing any instances of NA within the second grade
ordered.data.frame <- subset(ordered.data.frame, !(is.na(ordered.data.frame$Grade2)))

ordered.data.frame <- subset(ordered.data.frame, ordered.data.frame$Grade2 != "T")
```

```{r}
# Removing anyone who does not have 050 as a first course
ordered.data.frame <- subset(ordered.data.frame, ordered.data.frame$Course1 == "MA-050")
```

```{r}
# Removing anyone who has MA-100 as a second course since it is not a good indication of level 2 skills
ordered.data.frame <- subset(ordered.data.frame, ordered.data.frame$Course2 != "MA-100")
```


```{r}
tally( ~ (ordered.data.frame$Course1 == "MA-050") + ordered.data.frame$Course2, margins = TRUE, data = ordered.data.frame, format = 'count')
```


## Identifying Student Success
### Successful = C- or higher; identified as a 1
### Not Successful = Below C-; identified as a 0
```{r}
# Adding column for success identifier and making all of them initially show as successful
ordered.data.frame$Success <- 1
```

```{r}
# Replacing the success w/ "0" if the student had a second grade below a C-
for(i in 1:length(ordered.data.frame$Grade2)) {
  if(ordered.data.frame$Grade2[[i]] == "D+" || ordered.data.frame$Grade2[[i]] == "D" || ordered.data.frame$Grade2[[i]] == "D-" || ordered.data.frame$Grade2[[i]] == "F") {
    ordered.data.frame$Success[[i]] <- 0
  }
}
```

```{r}
# Grade in 050 vs Grade in level 2 course
tally(~ ordered.data.frame$Grade1 + ordered.data.frame$Grade2, margins = TRUE)
```

```{r}

tally(~ ordered.data.frame$Grade1 + ordered.data.frame$Success, margins = TRUE)
```

